// demo/react-shadcn-mf/level2/src/components/FlipMatchStar.tsx
import { useEffect, useRef, useState } from 'react'

interface Card { id: string; pairId: string; emoji: string }
interface Props { cards: Card[]; onComplete: () => void }

export default function FlipMatchStar({ cards, onComplete }: Props) {
  const [flipped, setFlipped] = useState<Set<string>>(new Set())
  const [matched, setMatched] = useState<Set<string>>(new Set())
  const [attempts, setAttempts] = useState(0)
  const [lock, setLock] = useState(false)
  const completedRef = useRef(false)

  useEffect(() => {
    if (!completedRef.current && matched.size === cards.length && cards.length > 0) {
      completedRef.current = true
      requestAnimationFrame(() => onComplete())
    }
  }, [matched, cards.length, onComplete])

  const click = (c: Card) => {
    if (lock || matched.has(c.id) || flipped.has(c.id)) return
    const nf = new Set(flipped); nf.add(c.id); setFlipped(nf)
    if (nf.size === 2) {
      setAttempts((a) => a + 1); setLock(true)
      const [a, b] = [...nf]
      const ca = cards.find((x) => x.id === a)!; const cb = cards.find((x) => x.id === b)!
      if (ca.pairId === cb.pairId) {
        setTimeout(() => {
          setMatched((m) => { const nm = new Set(m); nm.add(a); nm.add(b); return nm })
          setFlipped(new Set()); setLock(false)
        }, 400)
      } else {
        setTimeout(() => { setFlipped(new Set()); setLock(false) }, 800)
      }
    }
  }

  return (
    <div className="bg-white/80 rounded-lg p-2 shadow">
      <div className="grid grid-cols-3 gap-1.5">
        {cards.map((c) => {
          const up = flipped.has(c.id) || matched.has(c.id)
          return (
            <button key={c.id} onClick={() => click(c)} disabled={matched.has(c.id)} className="flip-card relative w-12 h-14 [perspective:600px]" aria-label="card">
              <div className="relative w-full h-full transition-transform duration-300 [transform-style:preserve-3d]"
                style={{ transform: up ? 'rotateY(180deg)' : 'rotateY(0deg)' }}>
                <div className="absolute inset-0 rounded-md bg-slate-700 [backface-visibility:hidden] flex items-center justify-center text-white text-lg">?</div>
                <div className="absolute inset-0 rounded-md bg-white border border-slate-200 [backface-visibility:hidden] [transform:rotateY(180deg)] flex items-center justify-center text-xl">{c.emoji}</div>
              </div>
            </button>
          )
        })}
      </div>
      <p className="text-[10px] text-slate-500 mt-1 text-center">尝试 {attempts}</p>
    </div>
  )
}

// demo/vue-shadcn/src/components/FlipMatchStar.vue
<script setup lang="ts">
import { ref } from 'vue'

interface Card { id: string; pairId: string; emoji: string }

const props = defineProps<{ cards: Card[] }>()
const emit = defineEmits<{ complete: [] }>()

const flipped = ref(new Set<string>())
const matched = ref(new Set<string>())
const attempts = ref(0)
const lock = ref(false)

function click(c: Card) {
  if (lock.value || matched.value.has(c.id) || flipped.value.has(c.id)) return
  const nf = new Set(flipped.value)
  nf.add(c.id)
  flipped.value = nf
  if (nf.size === 2) {
    attempts.value++
    lock.value = true
    const [a, b] = [...nf]
    const ca = props.cards.find((x) => x.id === a)!
    const cb = props.cards.find((x) => x.id === b)!
    if (ca.pairId === cb.pairId) {
      setTimeout(() => {
        const nm = new Set(matched.value)
        nm.add(a)
        nm.add(b)
        matched.value = nm
        if (nm.size === props.cards.length) emit('complete')
        flipped.value = new Set()
        lock.value = false
      }, 400)
    } else {
      setTimeout(() => {
        flipped.value = new Set()
        lock.value = false
      }, 800)
    }
  }
}

function isUp(id: string) { return flipped.value.has(id) || matched.value.has(id) }
</script>

<template>
  <div class="bg-white/80 rounded-lg p-2 shadow">
    <div class="grid grid-cols-3 gap-1.5">
      <button
        v-for="c in cards"
        :key="c.id"
        class="flip-card relative w-12 h-14"
        style="perspective: 600px"
        :disabled="matched.has(c.id)"
        aria-label="card"
        @click="click(c)"
      >
        <div
          class="relative w-full h-full transition-transform duration-300"
          style="transform-style: preserve-3d"
          :style="{ transform: isUp(c.id) ? 'rotateY(180deg)' : 'rotateY(0deg)' }"
        >
          <div
            class="absolute inset-0 rounded-md bg-slate-700 flex items-center justify-center text-white text-lg"
            style="backface-visibility: hidden"
          >?</div>
          <div
            class="absolute inset-0 rounded-md bg-white border border-slate-200 flex items-center justify-center text-xl"
            style="backface-visibility: hidden; transform: rotateY(180deg)"
          >{{ c.emoji }}</div>
        </div>
      </button>
    </div>
    <p class="text-[10px] text-slate-500 mt-1 text-center">尝试 {{ attempts }}</p>
  </div>
</template>
