// demo/react-shadcn/src/components/HotspotStar.tsx
import { useState } from 'react'

const ARROW: Record<string, string> = { up: '↑', down: '↓', left: '←', right: '→' }

interface Props {
  regions: { id: string; dir: 'up' | 'down' | 'left' | 'right' }[]
  correctId: string
  onComplete: () => void
}

export default function HotspotStar({ regions, correctId, onComplete }: Props) {
  const [picked, setPicked] = useState<string | null>(null)
  const [wrong, setWrong] = useState<string | null>(null)

  const pick = (id: string) => {
    if (picked) return
    if (id === correctId) {
      setPicked(id)
      onComplete()
    } else {
      setWrong(id)
      setTimeout(() => setWrong(null), 400)
    }
  }

  return (
    <div className="bg-white/80 rounded-lg p-2 shadow">
      <div className="grid grid-cols-2 gap-1.5">
        {regions.map((r) => (
          <button
            key={r.id}
            onClick={() => pick(r.id)}
            disabled={!!picked}
            className={`w-11 h-11 rounded-md border-2 text-xl flex items-center justify-center transition ${
              picked === r.id
                ? 'bg-green-500 border-green-600 text-white'
                : wrong === r.id
                ? 'bg-red-400 border-red-500 text-white animate-shake'
                : 'bg-white border-slate-300 hover:border-slate-500'
            }`}
          >{ARROW[r.dir]}</button>
        ))}
      </div>
    </div>
  )
}

// demo/vue-shadcn/src/components/HotspotStar.vue
<script setup lang="ts">
import { ref } from 'vue'

const ARROW: Record<string, string> = { up: '↑', down: '↓', left: '←', right: '→' }

const props = defineProps<{
  regions: { id: string; dir: 'up' | 'down' | 'left' | 'right' }[]
  correctId: string
}>()
const emit = defineEmits<{ complete: [] }>()

const picked = ref<string | null>(null)
const wrong = ref<string | null>(null)

function pick(id: string) {
  if (picked.value) return
  if (id === props.correctId) {
    picked.value = id
    emit('complete')
  } else {
    wrong.value = id
    setTimeout(() => { wrong.value = null }, 400)
  }
}
</script>

<template>
  <div class="bg-white/80 rounded-lg p-2 shadow">
    <div class="grid grid-cols-2 gap-1.5">
      <button
        v-for="r in regions"
        :key="r.id"
        :disabled="!!picked"
        class="w-11 h-11 rounded-md border-2 text-xl flex items-center justify-center transition"
        :class="
          picked === r.id
            ? 'bg-green-500 border-green-600 text-white'
            : wrong === r.id
            ? 'bg-red-400 border-red-500 text-white animate-shake'
            : 'bg-white border-slate-300 hover:border-slate-500'
        "
        @click="pick(r.id)"
      >{{ ARROW[r.dir] }}</button>
    </div>
  </div>
</template>
