// demo/react-mui/src/components/ModalStack.tsx
import { Box, Typography, Button, Dialog, DialogContent } from '@mui/material'

export type ModalType = 'page-complete' | 'final' | 'help'

export interface ModalEntry {
  type: ModalType
  score?: number
  levelName?: string   // e.g. "第 1 关"
  levelId?: number     // e.g. 1
}

interface Props {
  stack: ModalEntry[]
  totalScore: number
  onClose: () => void
  onNextLevel: () => void
  onRestart: () => void
}

function PageCompleteContent({ entry, onClose, onNextLevel }: { entry: ModalEntry; onClose: () => void; onNextLevel: () => void }) {
  return (
    <Box sx={{ textAlign: 'center', p: 2 }}>
      <Typography variant="h4" sx={{ mb: 1 }}>🎉</Typography>
      <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>第 {entry.levelId} 关完成</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>⭐⭐⭐</Typography>
      <Box sx={{ display: 'flex', gap: 1, justifyContent: 'center' }}>
        <Button variant="outlined" onClick={onClose} sx={{ borderColor: 'grey.400' }}>重玩</Button>
        <Button variant="contained" onClick={onNextLevel} sx={{ bgcolor: '#1e293b', '&:hover': { bgcolor: '#334155' } }}>下一关</Button>
      </Box>
    </Box>
  )
}

function FinalContent({ totalScore, onRestart }: { totalScore: number; onRestart: () => void }) {
  const hasBadge = totalScore >= 8
  return (
    <Box sx={{ textAlign: 'center', p: 2 }}>
      <Typography variant="h4" sx={{ mb: 1 }}>🏆</Typography>
      <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>全部完成</Typography>
      <Typography variant="body1" sx={{ mb: 0.5 }}>总分 <b>{totalScore}</b></Typography>
      {hasBadge && (
        <Typography variant="body2" color="success.main" sx={{ mb: 1.5 }}>🏅 徽章解锁</Typography>
      )}
      <Button variant="contained" onClick={onRestart} sx={{ bgcolor: '#1e293b', '&:hover': { bgcolor: '#334155' }, mt: 1 }}>
        重玩全部
      </Button>
    </Box>
  )
}

function HelpContent({ onClose }: { onClose: () => void }) {
  return (
    <Box sx={{ textAlign: 'center', p: 2 }}>
      <Typography variant="h6" sx={{ fontWeight: 700, mb: 1 }}>玩法</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'left', lineHeight: 1.8 }}>
        拖拽：把图标拖到虚线框。<br />
        翻牌：翻开两张配对。<br />
        热点：点正确方向。<br />
        测验：选正确答案。<br />
        完成所有星过关；Escape 关弹窗。
      </Typography>
      <Button variant="outlined" onClick={onClose} sx={{ borderColor: 'grey.400', mt: 2 }}>知道了</Button>
    </Box>
  )
}

export default function ModalStack({ stack, totalScore, onClose, onNextLevel, onRestart }: Props) {
  if (stack.length === 0) return null

  return (
    <>
      {stack.map((entry, index) => {
        const zBase = 1300
        return (
          <Dialog
            key={`${entry.type}-${index}`}
            open={true}
            disableEscapeKeyDown={true}
            onClose={() => {}}
            PaperProps={{
              sx: { borderRadius: 3, width: '288px', maxWidth: '90vw' },
            }}
            sx={{ zIndex: zBase + index * 10 }}
          >
            <DialogContent sx={{ p: 0 }}>
              {entry.type === 'page-complete' && (
                <PageCompleteContent entry={entry} onClose={onClose} onNextLevel={onNextLevel} />
              )}
              {entry.type === 'final' && (
                <FinalContent totalScore={totalScore} onRestart={onRestart} />
              )}
              {entry.type === 'help' && (
                <HelpContent onClose={onClose} />
              )}
            </DialogContent>
          </Dialog>
        )
      })}
    </>
  )
}

// demo/vue-shadcn/src/components/ModalStack.vue
<script lang="ts">
export interface Modal {
  id: string
  kind: 'page-complete' | 'final' | 'help'
  rating?: number
  score?: number
  total?: number
  badge?: boolean
}
</script>

<script setup lang="ts">
defineProps<{
  modals: Modal[]
}>()

defineEmits<{
  close: []
  next: []
  replay: []
  replayAll: []
}>()
</script>

<template>
  <template v-for="(m, i) in modals" :key="m.id">
    <div
      class="fixed inset-0 bg-black/40 flex items-center justify-center"
      :style="{ zIndex: 50 + i }"
      @click="$emit('close')"
    >
      <div class="bg-white rounded-2xl shadow-xl p-6 w-72 text-center" @click.stop>
        <template v-if="m.kind === 'page-complete'">
          <div class="text-4xl mb-2">🎉</div>
          <h2 class="text-xl font-bold text-slate-800">第 {{ m.total }} 关完成！</h2>
          <p class="text-2xl mt-1">{{ '⭐'.repeat(m.rating || 1) }}{{ '☆'.repeat(3 - (m.rating || 1)) }}</p>
          <div class="flex gap-2 mt-4 justify-center">
            <button class="px-4 py-2 rounded-md border border-slate-300 text-slate-700 hover:bg-slate-50" @click="$emit('replay')">重玩</button>
            <button class="px-4 py-2 rounded-md bg-slate-900 text-white hover:bg-slate-700" @click="$emit('next')">下一关</button>
          </div>
        </template>
        <template v-else-if="m.kind === 'final'">
          <div class="text-4xl mb-2">🏆</div>
          <h2 class="text-xl font-bold text-slate-800">全部完成！</h2>
          <p class="text-slate-500 mt-1">总分 <span class="font-bold text-slate-800">{{ m.score }}</span></p>
          <p class="text-2xl mt-2">{{ m.badge ? '🏅 徽章解锁' : '' }}</p>
          <div class="flex gap-2 mt-4 justify-center">
            <button class="px-4 py-2 rounded-md bg-slate-900 text-white hover:bg-slate-700" @click="$emit('replayAll')">重玩全部</button>
          </div>
        </template>
        <template v-else-if="m.kind === 'help'">
          <h2 class="text-lg font-bold text-slate-800 mb-2">玩法</h2>
          <p class="text-sm text-slate-600 text-left leading-relaxed">
            拖拽：把图标拖到虚线框。<br>
            翻牌：翻开两张配对。<br>
            热点：点正确方向。<br>
            测验：选正确答案。<br>
            完成所有星过关；Escape 关弹窗。
          </p>
          <div class="mt-4">
            <button class="px-4 py-2 rounded-md bg-slate-900 text-white" @click="$emit('close')">知道了</button>
          </div>
        </template>
      </div>
    </div>
  </template>
</template>
