// demo/react-mui/src/App.tsx
import { useState, useEffect, useCallback } from 'react'
import { Box } from '@mui/material'
import { LEVELS } from './data/levels'
import { loadProgress, saveProgress, clearProgress } from './lib/storage'
import DragFillStar from './components/DragFillStar'
import FlipMatchStar from './components/FlipMatchStar'
import HotspotStar from './components/HotspotStar'
import QuizStar from './components/QuizStar'
import ModalStack, { type ModalEntry } from './components/ModalStack'
import Header from './components/Header'
import PageNav from './components/PageNav'
import Confetti from './components/Confetti'
import type { Star } from './data/levels'

function StarView({ star, onComplete }: { star: Star; onComplete: () => void }) {
  if (star.type === 'drag-fill' && star.dragFill)
    return <Box sx={{ width: 224, height: 160, bgcolor: 'rgba(255,255,255,0.2)', borderRadius: 1 }}><DragFillStar data={star.dragFill} onComplete={onComplete} /></Box>
  if (star.type === 'flip-match' && star.flipMatch)
    return <FlipMatchStar data={star.flipMatch} onComplete={onComplete} />
  if (star.type === 'hotspot' && star.hotspot)
    return <HotspotStar data={star.hotspot} onComplete={onComplete} />
  if (star.type === 'quiz-single' && star.quiz)
    return <QuizStar data={star.quiz} onComplete={onComplete} />
  return null
}

export default function App() {
  const [levelIdx, setLevelIdx] = useState(() => {
    const p = loadProgress()
    return p ? Math.min(p.currentLevel, LEVELS.length - 1) : 0
  })
  const [completed, setCompleted] = useState<Set<string>>(() => {
    const p = loadProgress()
    return new Set(p?.completed ?? [])
  })
  const [modalStack, setModalStack] = useState<ModalEntry[]>([])
  const [confetti, setConfetti] = useState(0)
  const [round, setRound] = useState(0)

  const level = LEVELS[levelIdx]
  const totalScore = completed.size
  const badge = totalScore >= 8
  const allDone = LEVELS.every(lv => lv.stars.every(s => completed.has(s.id)))

  useEffect(() => {
    saveProgress({ currentLevel: levelIdx, completed: [...completed] })
  }, [levelIdx, completed])

  useEffect(() => {
    const levelNowDone = level.stars.every(s => completed.has(s.id))
    if (!levelNowDone) return
    if (modalStack.some(m => m.type === 'page-complete' || m.type === 'final')) return
    setConfetti(c => c + 1)
    if (allDone) {
      setModalStack(ms => [...ms, { type: 'final', score: totalScore }])
    } else {
      setModalStack(ms => [...ms, { type: 'page-complete', levelId: level.id }])
    }
  }, [completed]) // eslint-disable-line

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setModalStack(m => m.slice(0, -1))
    }
    window.addEventListener('keydown', onKey, true)
    return () => window.removeEventListener('keydown', onKey, true)
  }, [])

  const completeStar = useCallback((id: string) => {
    setCompleted(prev => {
      if (prev.has(id)) return prev
      return new Set([...prev, id])
    })
  }, [])

  const closeTop = useCallback(() => setModalStack(m => m.slice(0, -1)), [])
  const openHelp = () => setModalStack(ms => [...ms, { type: 'help' }])
  const goNext = () => {
    setModalStack(m => m.slice(0, -1))
    setLevelIdx(i => Math.min(LEVELS.length - 1, i + 1))
  }
  const restart = () => {
    setModalStack([])
    setCompleted(new Set())
    setLevelIdx(0)
    setRound(r => r + 1)
    clearProgress()
  }

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'grey.100', p: 2, display: 'flex', flexDirection: 'column', alignItems: 'center', fontFamily: 'sans-serif' }}>
      <Header
        level={level.id}
        totalLevels={LEVELS.length}
        score={totalScore}
        hasBadge={badge}
        onHelp={openHelp}
      />
      <Box
        key={`${levelIdx}-${round}`}
        sx={{
          position: 'relative',
          width: '100%',
          maxWidth: 768,
          aspectRatio: '4 / 3',
          borderRadius: 4,
          boxShadow: 3,
          overflow: 'hidden',
          background: level.bg,
          transition: 'all 0.3s',
        }}
      >
        {level.stars.map((star) => (
          <Box
            key={`${levelIdx}-${round}-${star.id}`}
            sx={{
              position: 'absolute',
              left: `${star.pos.x * 100}%`,
              top: `${star.pos.y * 100}%`,
              transform: 'translate(-50%,-50%)',
            }}
          >
            <StarView star={star} onComplete={() => completeStar(star.id)} />
          </Box>
        ))}
      </Box>
      <PageNav
        currentIndex={levelIdx}
        total={LEVELS.length}
        onPrev={() => setLevelIdx(i => Math.max(0, i - 1))}
        onNext={() => setLevelIdx(i => Math.min(LEVELS.length - 1, i + 1))}
      />
      <ModalStack
        stack={modalStack}
        totalScore={totalScore}
        onClose={closeTop}
        onNextLevel={goNext}
        onRestart={restart}
      />
      {confetti > 0 && <Confetti key={confetti} />}
    </Box>
  )
}

// demo/vue-shadcn/src/App.vue
<script setup lang="ts">
import { ref, computed, watchEffect, onMounted, onUnmounted } from 'vue'
import { LEVELS } from './data/levels'
import { loadProgress, saveProgress, clearProgress } from './lib/storage'
import type { Progress } from './lib/storage'
import Header from './components/Header.vue'
import PageNav from './components/PageNav.vue'
import DragFillStar from './components/DragFillStar.vue'
import FlipMatchStar from './components/FlipMatchStar.vue'
import HotspotStar from './components/HotspotStar.vue'
import QuizStar from './components/QuizStar.vue'
import ModalStack from './components/ModalStack.vue'
import type { Modal } from './components/ModalStack.vue'
import Confetti from './components/Confetti.vue'

// --- init from localStorage ---
let mid = 0
const newModal = (m: Omit<Modal, 'id'>): Modal => ({ ...m, id: `m${++mid}` })

const savedProgress = loadProgress()

const levelIdx = ref(savedProgress ? Math.min(savedProgress.level, LEVELS.length - 1) : 0)

function initCompleted(): Record<number, Set<string>> {
  const c: Record<number, Set<string>> = {}
  if (savedProgress?.completed) {
    Object.entries(savedProgress.completed).forEach(([k, v]) => { c[+k] = new Set(v) })
  }
  return c
}

const completed = ref<Record<number, Set<string>>>(initCompleted())

const ratings = ref<Record<number, number>>(savedProgress?.ratings ?? {})
const modals = ref<Modal[]>([])
const confetti = ref(0)
const round = ref(0)

// --- computed ---
const level = computed(() => LEVELS[levelIdx.value])
const doneSet = computed(() => completed.value[levelIdx.value] ?? new Set<string>())
const doneCount = computed(() => doneSet.value.size)
const totalScore = computed(() => Object.values(completed.value).reduce((s, set) => s + set.size, 0))
const allLevelsDone = computed(() => LEVELS.every((lv, i) => (completed.value[i]?.size ?? 0) >= lv.stars.length))
const badge = computed(() => totalScore.value >= 8)

// --- persistence ---
watchEffect(() => {
  const p: Progress = {
    level: levelIdx.value,
    completed: Object.fromEntries(
      Object.entries(completed.value).map(([k, v]) => [k, [...v]])
    ) as Record<number, string[]>,
    ratings: ratings.value,
    total: totalScore.value,
  }
  saveProgress(p)
})

// --- level completion watcher ---
watchEffect(() => {
  if (doneCount.value >= level.value.stars.length && !ratings.value[levelIdx.value]) {
    ratings.value = { ...ratings.value, [levelIdx.value]: 3 }
    confetti.value++
    if (!allLevelsDone.value) {
      modals.value = [...modals.value, newModal({ kind: 'page-complete', rating: 3, total: level.value.id })]
    }
  }
})

// --- final modal watcher ---
watchEffect(() => {
  if (allLevelsDone.value && !modals.value.some((m) => m.kind === 'final')) {
    modals.value = [...modals.value, newModal({ kind: 'final', score: totalScore.value, badge: badge.value })]
  }
})

// --- keyboard ---
function onKey(e: KeyboardEvent) {
  if (e.key === 'Escape' && modals.value.length) {
    modals.value = modals.value.slice(0, -1)
  }
}
onMounted(() => window.addEventListener('keydown', onKey))
onUnmounted(() => window.removeEventListener('keydown', onKey))

// --- actions ---
function completeStar(starId: string) {
  const cur = new Set(completed.value[levelIdx.value] ?? [])
  if (cur.has(starId)) return
  cur.add(starId)
  completed.value = { ...completed.value, [levelIdx.value]: cur }
}

function closeTop() { modals.value = modals.value.slice(0, -1) }
function openHelp() { modals.value = [...modals.value, newModal({ kind: 'help' })] }
function nextLevel() {
  modals.value = modals.value.slice(0, -1)
  levelIdx.value = Math.min(LEVELS.length - 1, levelIdx.value + 1)
}
function replayLevel() {
  modals.value = modals.value.slice(0, -1)
  completed.value = { ...completed.value, [levelIdx.value]: new Set() }
  const r = { ...ratings.value }
  delete r[levelIdx.value]
  ratings.value = r
  round.value++
}
function replayAll() {
  modals.value = []
  completed.value = {}
  ratings.value = {}
  levelIdx.value = 0
  round.value++
  clearProgress()
}
function onNavChange(lvl: number) { levelIdx.value = lvl - 1 }
</script>

<template>
  <div class="min-h-screen bg-slate-100 p-4 flex flex-col items-center font-sans">
    <Header :level="level.id" :total="LEVELS.length" :score="totalScore" :badge="badge" @help="openHelp" />

    <div
      :key="levelIdx"
      class="relative w-full max-w-3xl rounded-2xl shadow-lg overflow-hidden transition-all duration-300"
      :style="{ background: level.bg, aspectRatio: '4 / 3' }"
    >
      <div
        v-for="star in level.stars"
        :key="`${levelIdx}-${round}-${star.id}`"
        class="absolute"
        :style="{ left: `${star.pos.x * 100}%`, top: `${star.pos.y * 100}%`, transform: 'translate(-50%,-50%)' }"
      >
        <div v-if="star.type === 'drag-fill' && star.dragFill" class="w-56 h-40 bg-white/20 rounded-lg">
          <DragFillStar :pieces="star.dragFill.pieces" :slots="star.dragFill.slots" @complete="completeStar(star.id)" />
        </div>
        <FlipMatchStar
          v-else-if="star.type === 'flip-match' && star.flipMatch"
          :cards="star.flipMatch.cards"
          @complete="completeStar(star.id)"
        />
        <HotspotStar
          v-else-if="star.type === 'hotspot' && star.hotspot"
          :regions="star.hotspot.regions"
          :correct-id="star.hotspot.correctId"
          @complete="completeStar(star.id)"
        />
        <QuizStar
          v-else-if="star.type === 'quiz-single' && star.quiz"
          :question="star.quiz.question"
          :options="star.quiz.options"
          @complete="completeStar(star.id)"
        />
      </div>
    </div>

    <PageNav
      :level="level.id"
      :total="LEVELS.length"
      :dots="LEVELS.map((_, i) => (completed[i]?.size ?? 0) >= LEVELS[i].stars.length)"
      @change="onNavChange"
    />

    <ModalStack
      :modals="modals"
      @close="closeTop"
      @next="nextLevel"
      @replay="replayLevel"
      @replay-all="replayAll"
    />

    <Confetti :run="confetti" />
  </div>
</template>
