// demo/vue-shadcn/src/components/Header.vue
<script setup lang="ts">
defineProps<{
  level: number
  total: number
  score: number
  badge: boolean
}>()

defineEmits<{ help: [] }>()
</script>

<template>
  <header class="w-full max-w-3xl flex items-center justify-between mb-3">
    <div class="flex items-center gap-2">
      <h1 class="text-lg font-bold text-slate-800">Epic Labs</h1>
      <span class="text-xs px-2 py-0.5 rounded-full bg-slate-200 text-slate-600">Lv {{ level }}/{{ total }}</span>
    </div>
    <div class="flex items-center gap-3">
      <span class="text-sm">⭐ {{ score }}</span>
      <span class="text-lg" :title="badge ? '徽章已解锁' : '未解锁'">{{ badge ? '🏆' : '▪️' }}</span>
      <button
        class="help-btn w-7 h-7 rounded-full border border-slate-300 text-slate-600 hover:bg-slate-100 flex items-center justify-center"
        aria-label="帮助"
        @click="$emit('help')"
      >?</button>
    </div>
  </header>
</template>

// demo/react-mui/src/components/Header.tsx
import { Box, Typography } from '@mui/material'

interface Props {
  level: number
  totalLevels: number
  score: number
  hasBadge: boolean
  onHelp: () => void
}

export default function Header({ level, totalLevels, score, hasBadge, onHelp }: Props) {
  return (
    <Box sx={{ display:'flex', alignItems:'center', justifyContent:'space-between', width:'100%', maxWidth:768, mb:2, px:1 }}>
      <Box sx={{ display:'flex', alignItems:'center', gap:1 }}>
        <Typography variant="h6" sx={{ fontWeight:700 }}>Epic Labs</Typography>
        <Box sx={{ px:1, py:0.25, borderRadius:8, bgcolor:'grey.200' }}>
          <Typography variant="caption" sx={{ color:'grey.600' }}>Lv {level}/{totalLevels}</Typography>
        </Box>
      </Box>
      <Box sx={{ display:'flex', alignItems:'center', gap:1.5 }}>
        <Typography variant="body2">⭐ {score}</Typography>
        <Typography variant="body1" title={hasBadge ? '徽章已解锁' : '未解锁'}>{hasBadge ? '🏆' : '▪️'}</Typography>
        <button
          className="help-btn"
          aria-label="帮助"
          onClick={onHelp}
          style={{ width:28, height:28, borderRadius:'50%', border:'1px solid #cbd5e1', background:'white', cursor:'pointer', fontSize:14, color:'#475569', display:'flex', alignItems:'center', justifyContent:'center' }}
        >?</button>
      </Box>
    </Box>
  )
}
